// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: post.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO post (
    id,
    created_at,
    updated_at,
    title,
    description,
    url,
    published_at,
    feed_id
)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
    RETURNING id, created_at, updated_at, title, description, url, published_at, feed_id
`

type CreatePostParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description sql.NullString
	Url         string
	PublishedAt time.Time
	FeedID      uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.PublishedAt,
		arg.FeedID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.PublishedAt,
		&i.FeedID,
	)
	return i, err
}

const getPostsForAccount = `-- name: GetPostsForAccount :many
SELECT post.id, post.created_at, post.updated_at, post.title, post.description, post.url, post.published_at, post.feed_id FROM post
    JOIN feed_follow ON post.feed_id = feed_follow.feed_id
    WHERE feed_follow.account_id = $1
    ORDER BY post.published_at DESC 
    LIMIT $2
`

type GetPostsForAccountParams struct {
	AccountID uuid.UUID
	Limit     int32
}

func (q *Queries) GetPostsForAccount(ctx context.Context, arg GetPostsForAccountParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForAccount, arg.AccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
